### PR TITLE
Module Update

### PR DESCRIPTION
**Pull request by yayza**
Made some changes to how the configuration is done:

- Replaced `config.ini` with an object in `lib/config.js`
- `listServer.js` now loads the new config file via a `require` module
- Removed `translateConfigOptionToBool`, as it's not required anymore
- Removed the `multi-ini` dependency, as it's not required anymore either

Other Changes:
- Express has it's own body parser implementation so I removed the extra dependency.
- Added a config option `ipv4` to and set default as true to listen for ipv4 only

### CODE REVIEW

**Comment by SoftwareGuy** [comment]
+666 lines... 😮 

I'll probably bump the version to 2.1 after this PR as it's quite a cleanup and tidy up.

Is this ready to merge or do you still need to tidy things up?

**Comment by yayza** [comment]
> +666 lines... 😮
> 
> I'll probably bump the version to 2.1 after this PR as it's quite a cleanup and tidy up.
> 
> Is this ready to merge or do you still need to tidy things up?

I had to do a double take myself lol. 641 lines were generated by npm and added to the package-lock.json file.  (Usually when someone changes package.json or runs `npm install` and npm installs the latest versions of the required packages their own dependencies might have changed as well so those get added/updated to package-lock.json)

EDIT: If you're going to bump the version, I'll add some more code splits tomorrow to that lib folder. (Or you can merge this one since is config specific and I can put that in a seperate PR)

**Comment by SoftwareGuy** [comment]
Looking really good. I'm liking this modular approach refactor.

**Comment by yayza** [comment]
Thanks ! Almost finished with this one , gonna clean it up tomorrow and it'll be ready to merge.

**Comment by yayza** [comment]
General
- Added eslint config file
- Added option to package.json to just run `npm start` in terminal to load the main file

Config
- Replaced config.ini with lib/config.js
- Added comments for all the options in config
- Added `sendNextPruneTimeInSeconds` to config. This option takes a bool and is used to specify whether
  we should send the remaining amount of time a server has left (in secionds) before it's removed from the list.
  This is useful when a server is added to the list and crashes too soon and loses it's uuid, when it tries
  to re-add itself it will know now how long to wait before retrying the `/add` path. 


Logger
- Moved logger code to lib/logger.js. Didn't make any changes here.

Express
- Moved code related to express server to lib/express.js
- Added two middleware functions (imported from requestHandlers.js) that the express server must send requests to
  before passing them to the their respective path's functions.

New Files
- lib/requestHandlers.js - the middleware functions described above. 
- lib/validators.js - instead of writing out all the validations in requestHandlers.js, (would've gotten messy)
  I decided to make them their own file and just import them wherever they're required.
- lib/utils.js - just some helper variables / functions
- lib/serverList.js - This is pretty much where all the main action happens, it's an object that contains listServer.js's main 
    functionality and some rewritten pruning functionality to account for async behavior + the `sendNextPruneTimeInSeconds` feature explained in the Config section

listServer.js
- Renamed listServer.js to init.js
- Pretty much stripped it all the way down to intialization, 90% of the code was moved into their respective module in the libs folder

**Comment by SoftwareGuy** [comment]
All good with this? I'll push it if you're good to go.

**Comment by MuhammedKAldin** [comment]
Yep, its ready now 👍

**Comment by yayza** [comment]
Yup, it's ready now !

**Pull request merged**
